dist: trusty
sudo: false
language: python
python:
- '3.4'

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "lukasg18-github"
    token:
      secure: "$SONAR_TOKEN"
# services:
# - postgres

branches:
  only:
  - master
  - lucas

install:
- pip install -r requeriments.pip

script:
# - cd wsgi/gde
- python manage.py makemigrations
- python manage.py migrate
- sonar-scanner
